import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  vrmSidebar: [{ type: 'autogenerated', dirName: 'vrm' }],
  gltfSidebar: [{ type: 'autogenerated', dirName: 'gltf' }],
  univrmSidebar: [{ type: 'autogenerated', dirName: 'univrm' }],
  univrm1Sidebar: [{ type: 'autogenerated', dirName: 'univrm1' }],
  vrm1Sidebar: [{ type: 'autogenerated', dirName: 'vrm1' }],

  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
  implSidebar: [{ type: 'autogenerated', dirName: 'implementation' }],
  unihumanoidSidebar: [{ type: 'autogenerated', dirName: 'unihumanoid' }],
  releaseSidebar: [{ type: 'autogenerated', dirName: 'release' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
