import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  vrmSidebar: [
    {
      type: 'category',
      label: 'vrmについて',
      items: [
        { type: 'doc', id: 'vrm/vrm_about' },
        {
          type: 'category',
          label: 'VRMファイルを作ってみたい',
          link: { type: 'doc', id: 'vrm/how_to_make_vrm/index' },
          items: [
            { type: 'doc', id: 'vrm/how_to_make_vrm/setup_unity' },
            { type: 'doc', id: 'vrm/how_to_make_vrm/convert_from_humanoid_model' },
            { type: 'doc', id: 'vrm/how_to_make_vrm/setup_vrm' },
            { type: 'doc', id: 'vrm/how_to_make_vrm/vrm_behavior_confirmation' },
          ],
        },
        { type: 'doc', id: 'vrm/how_to_view_vrm' },
        { type: 'doc', id: 'vrm/vrm_applications' },
        { type: 'doc', id: 'vrm/vrm_meta' },
        { type: 'doc', id: 'vrm/vrm_development' },
      ],
    },
    // { type: 'autogenerated', dirName: 'vrm' }
  ],
  gltfSidebar: [{ type: 'autogenerated', dirName: 'gltf' }],
  univrmSidebar: [{ type: 'autogenerated', dirName: 'univrm' }],
  univrm1Sidebar: [{ type: 'autogenerated', dirName: 'univrm1' }],
  vrm1Sidebar: [{ type: 'autogenerated', dirName: 'vrm1' }],

  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],
  implSidebar: [{ type: 'autogenerated', dirName: 'implementation' }],
  unihumanoidSidebar: [{ type: 'autogenerated', dirName: 'unihumanoid' }],
  releaseSidebar: [{ type: 'autogenerated', dirName: 'release' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
